name: Release PyPI Version

on:
  push:
    tags:
      - "*.*.*"
jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.11
          architecture: x64
          prerelease: true
          enable-pep582: true
          cache: true
      - name: Run build
        run: pdm build
      - name: Publish version
        run: pdm publish --username __token__ --password ${{secrets.PYPI_TOKEN}}
